import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "./App";

const prompts = ["Summarize the current fraud analysis", "Find suspicious money flow patterns", "Explain fan-in and fan-out activity", "Show me the highest-priority investigations", "How can I trace funds between accounts?", "Explain the current risk scoring rules"];

function AssistantChatLegacy() {
  const navigate = useNavigate(); const [open, setOpen] = useState(false); const [text, setText] = useState(""); const [messages, setMessages] = useState([]); const [sending, setSending] = useState(false); const [error, setError] = useState(""); const bottom = useRef(null);
  useEffect(() => { if (open) bottom.current?.scrollIntoView({ behavior: "smooth" }); }, [open, messages, sending]);
  const send = async value => { const message = value.trim(); if (!message || sending) return; setMessages(current => [...current, { role: "user", content: message, at: new Date().toISOString() }]); setText(""); setSending(true); setError(""); try { const result = (await api.post("/api/assistant/chat", { message })).data; setMessages(current => [...current, { role: "assistant", content: result.response, label: result.label, actions: result.actions || [], at: new Date().toISOString() }]); } catch (exception) { setError(exception.response?.data?.detail || "The assistant could not respond. Try again."); } finally { setSending(false); } };
  const clear = () => { if (messages.length && !confirm("Clear this local conversation view?")) return; setMessages([]); setError(""); };
  return <div className={`assistant-dock ${open ? "open" : ""}`}><button className="assistant-fab" onClick={() => setOpen(value => !value)} aria-label={open ? "Close UNDERTOW AI" : "Open UNDERTOW AI"}>{open ? "×" : "✦"}<span>AI</span></button>{open && <section className="assistant-panel" aria-label="UNDERTOW AI chat"><header><div className="assistant-avatar">✦</div><div><b>UNDERTOW AI</b><small>Financial Investigation Assistant</small></div><button className="assistant-clear" onClick={clear}>Clear</button></header><div className="assistant-messages">{!messages.length && <div className="assistant-welcome"><p>I can explain the current authorised analysis, accounts, rules, investigation queue, and fund tracing. I do not make case decisions.</p><div>{prompts.map(prompt => <button key={prompt} onClick={() => send(prompt)}>{prompt}</button>)}</div></div>}{messages.map((message, index) => <article className={`assistant-message ${message.role}`} key={`${message.at}-${index}`}><div>{message.content.split("\n").map((line, lineIndex) => <p key={lineIndex}>{line}</p>)}{message.label && <small>{message.label}</small>}{message.role === "assistant" && <button className="assistant-copy" onClick={() => navigator.clipboard?.writeText(message.content)}>Copy</button>}{message.actions?.map(action => <button className="assistant-action" key={action.label} onClick={() => navigate(action.route)}>{action.label}</button>)}</div><time>{new Date(message.at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time></article>)}{sending && <article className="assistant-message assistant"><div className="assistant-typing">Thinking…</div></article>}{error && <div className="assistant-error">{error}<button onClick={() => send(messages.at(-1)?.content || text)}>Retry</button></div>}<div ref={bottom}/></div><form onSubmit={event => { event.preventDefault(); send(text); }}><textarea value={text} onChange={event => setText(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); send(text); } }} placeholder="Ask about the current analysis…" aria-label="Message UNDERTOW AI" rows="1"/><button disabled={!text.trim() || sending} type="submit">Send</button></form></section>}</div>;
}

const copilotPrompts = ["Why was the highest-risk account flagged?", "Summarize the current dataset", "Explain fan-in and fan-out simply", "Which alerts should an analyst review first?"];
export default function AssistantChat({ initialOpen = false }) {
  const navigate = useNavigate(); const [open, setOpen] = useState(initialOpen); const [text, setText] = useState(""); const [messages, setMessages] = useState([]); const [sending, setSending] = useState(false); const [error, setError] = useState(""); const [status, setStatus] = useState(null); const bottom = useRef(null);
  useEffect(() => { if (!open) return; api.get("/api/assistant/status").then(response => setStatus(response.data)).catch(() => setStatus({ configured: false, fallback: "Rule-based assistant — AI provider not configured" })); }, [open]);
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, sending, open]);
  const send = async value => { const message = value.trim(); if (!message || sending || message.length > 1500) return; setMessages(current => [...current, { role: "user", content: message, at: new Date().toISOString() }]); setText(""); setError(""); setSending(true); try { const result = (await api.post("/api/copilot/chat", { message })).data; setMessages(current => [...current, { role: "assistant", content: result.response, label: result.label, actions: result.actions || [], references: result.supporting_references || result.actions || [], at: new Date().toISOString() }]); } catch (exception) { const detail = exception.response?.data?.detail; const messageText = typeof detail === "string" ? detail : detail?.message; setError(messageText || (exception.response?.status === 404 ? "No active analysis is loaded. Import a CSV or load the synthetic demo dataset first." : "Copilot could not respond. Try again.")); } finally { setSending(false); } };
  const retry = () => { const last = [...messages].reverse().find(item => item.role === "user"); if (last) send(last.content); };
  return <div className={`assistant-dock ${open ? "open" : ""}`}><button className="assistant-fab" onClick={() => setOpen(value => !value)} aria-label={open ? "Close UNDERTOW Copilot" : "Open UNDERTOW Copilot"}>{open ? "×" : "✦"}<span>AI</span></button>{open && <section className="assistant-panel" aria-label="UNDERTOW AI Investigation Copilot"><header><div className="assistant-avatar">✦</div><div><b>UNDERTOW Copilot</b><small>{status?.configured ? `${status.provider} · ${status.model}` : "Rule-based fallback"}</small></div><button className="assistant-clear" onClick={() => { setMessages([]); setError(""); }}>Clear</button></header><div className="assistant-messages">{!messages.length && <div className="assistant-welcome"><p>Welcome to UNDERTOW Copilot. I can help explain transaction patterns, investigate connected accounts, and summarize evidence from your current dataset.</p><small className="assistant-mode">{status?.configured ? "AI provider configured · verify every answer against evidence" : "Rule-based assistant — AI provider not configured"}</small><div>{copilotPrompts.map(prompt => <button key={prompt} onClick={() => send(prompt)}>{prompt}</button>)}</div></div>}{messages.map((message, index) => <article className={`assistant-message ${message.role}`} key={`${message.at}-${index}`}><div>{message.content.split("\n").map((line, lineIndex) => <p key={lineIndex}>{line}</p>)}{message.label && <small>{message.label}</small>}{message.role === "assistant" && <><button className="assistant-copy" onClick={() => navigator.clipboard?.writeText(message.content)}>Copy</button>{message.references?.map(reference => <button className="assistant-action" key={`${reference.type}-${reference.id}`} onClick={() => navigate(reference.route)}>{reference.type}: {reference.id}</button>)}</>}</div><time>{new Date(message.at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time></article>)}{sending && <article className="assistant-message assistant"><div className="assistant-typing">Copilot is reviewing the authorised context…</div></article>}{error && <div className="assistant-error" role="alert">{error}<button onClick={retry}>Retry</button></div>}<div ref={bottom}/></div><form onSubmit={event => { event.preventDefault(); send(text); }}><textarea value={text} maxLength="1500" onChange={event => setText(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); send(text); } }} placeholder="Ask about the current analysis…" aria-label="Message UNDERTOW Copilot" rows="1"/><button disabled={!text.trim() || sending} type="submit">Send</button></form></section>}</div>;
}
