import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "./App";

const prompts = ["Summarize the current fraud analysis", "Find suspicious money flow patterns", "Explain fan-in and fan-out activity", "Show me the highest-priority investigations", "How can I trace funds between accounts?", "Explain the current risk scoring rules"];

export default function AssistantChat() {
  const navigate = useNavigate(); const [open, setOpen] = useState(false); const [text, setText] = useState(""); const [messages, setMessages] = useState([]); const [sending, setSending] = useState(false); const [error, setError] = useState(""); const bottom = useRef(null);
  useEffect(() => { if (open) bottom.current?.scrollIntoView({ behavior: "smooth" }); }, [open, messages, sending]);
  const send = async value => { const message = value.trim(); if (!message || sending) return; setMessages(current => [...current, { role: "user", content: message, at: new Date().toISOString() }]); setText(""); setSending(true); setError(""); try { const result = (await api.post("/api/assistant/chat", { message })).data; setMessages(current => [...current, { role: "assistant", content: result.response, label: result.label, actions: result.actions || [], at: new Date().toISOString() }]); } catch (exception) { setError(exception.response?.data?.detail || "The assistant could not respond. Try again."); } finally { setSending(false); } };
  const clear = () => { if (messages.length && !confirm("Clear this local conversation view?")) return; setMessages([]); setError(""); };
  return <div className={`assistant-dock ${open ? "open" : ""}`}><button className="assistant-fab" onClick={() => setOpen(value => !value)} aria-label={open ? "Close UNDERTOW AI" : "Open UNDERTOW AI"}>{open ? "×" : "✦"}<span>AI</span></button>{open && <section className="assistant-panel" aria-label="UNDERTOW AI chat"><header><div className="assistant-avatar">✦</div><div><b>UNDERTOW AI</b><small>Financial Investigation Assistant</small></div><button className="assistant-clear" onClick={clear}>Clear</button></header><div className="assistant-messages">{!messages.length && <div className="assistant-welcome"><p>I can explain the current authorised analysis, accounts, rules, investigation queue, and fund tracing. I do not make case decisions.</p><div>{prompts.map(prompt => <button key={prompt} onClick={() => send(prompt)}>{prompt}</button>)}</div></div>}{messages.map((message, index) => <article className={`assistant-message ${message.role}`} key={`${message.at}-${index}`}><div>{message.content.split("\n").map((line, lineIndex) => <p key={lineIndex}>{line}</p>)}{message.label && <small>{message.label}</small>}{message.role === "assistant" && <button className="assistant-copy" onClick={() => navigator.clipboard?.writeText(message.content)}>Copy</button>}{message.actions?.map(action => <button className="assistant-action" key={action.label} onClick={() => navigate(action.route)}>{action.label}</button>)}</div><time>{new Date(message.at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time></article>)}{sending && <article className="assistant-message assistant"><div className="assistant-typing">Thinking…</div></article>}{error && <div className="assistant-error">{error}<button onClick={() => send(messages.at(-1)?.content || text)}>Retry</button></div>}<div ref={bottom}/></div><form onSubmit={event => { event.preventDefault(); send(text); }}><textarea value={text} onChange={event => setText(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); send(text); } }} placeholder="Ask about the current analysis…" aria-label="Message UNDERTOW AI" rows="1"/><button disabled={!text.trim() || sending} type="submit">Send</button></form></section>}</div>;
}
